[#57] Implement Backend user authentication
nimblehq/js-framework-benchmark pull request #90
Opened 2023-05-26 04:09 UTC by phisith

https://github.com/nimblehq/js-framework-benchmark/issues/57

## What happened 👀

- Setup authentication (login using Google), 
- Save user information into database when login
- Add login url and protected route

## Insight 📝

To be able to setup the authentication I'm using the [remix-auth](https://www.npmjs.com/package/remix-auth) with [remix-auth-socials](https://www.npmjs.com/package/remix-auth-socials) (A collection of Remix Auth strategies for Oauth2 Social logins.).

In this setup I'm not able to use the `Passport.js`, due to Remix doesn't have the ability to control the server code like Nextjs. 

Reference:
![Screenshot 2566-05-23 at 17 58 36](https://github.com/nimblehq/js-framework-benchmark/assets/59072804/ba2a71f6-d04f-4797-9802-d87c13e8f8d6)

## Proof Of Work 📹
### Login Flow
https://github.com/nimblehq/js-framework-benchmark/assets/59072804/4f705730-4e75-462b-9168-73e26f2f49cf

### session is store in cookies
<img width="590" alt="Screenshot 2566-05-24 at 09 22 03" src="https://github.com/nimblehq/js-framework-benchmark/assets/59072804/f72d7f8e-3bf6-44ee-8ba1-63cc613192b6">

### Protected route (must login before access the route)
<img width="812" alt="Screenshot 2566-05-23 at 16 04 54" src="https://github.com/nimblehq/js-framework-benchmark/assets/59072804/cc4a3f3c-688f-407b-bd13-1e675761b0af">

2023-05-29 06:53 UTC, tednguyendev approved these changes

2023-05-29 07:00 UTC, olivierobert requested changes

2023-05-29 07:09 UTC, phisith commented on remix/app/services/session.server.ts
> +export const sessionStorage = createCookieSessionStorage({
Oh, I just forgot to remove it when I refactor the session.server 🙊.

Now removed.

2023-05-29 07:17 UTC, phisith commented on remix/app/routes/_index.tsx
> +    <div style={{ fontFamily: 'system-ui, sans-serif', lineHeight: '1.4' }}>
Well noted, Actually this styling is come with the default setup, so next time I will pay attention to it 👍🏼.

Removed.

2023-05-29 07:27 UTC, phisith commented on remix/app/repositories/user.server.test.ts
> +    describe('given there is a user information', () => {
Fixed.

2023-05-29 07:40 UTC, phisith commented on remix/app/services/auth.server.ts
> +  if (userProfile) {
For this one and the [question](https://github.com/nimblehq/js-framework-benchmark/pull/90#discussion_r1208982482) above is I have to return the profile for `remix-auth` as it require for the callback.

Short answer is: Yes, it handle by `remix-auth`.

2023-05-29 07:45 UTC, phisith commented on remix/app/services/auth.server.ts
> +}
Added.

2023-05-29 07:54 UTC, phisith commented on remix/app/routes/auth.google.callback.tsx
> +    failureRedirect: '/',
For this I actually done it same as you prefer in PR[#58], should I change here too or wait that PR merge ?

2023-05-29 07:56 UTC, phisith commented on remix/app/routes/newsletters.tsx
> +  const profile = (await authenticator.isAuthenticated(request)) as {
In this point I also have done it in PR [#58], But I will change here too.

2023-05-29 08:17 UTC, olivierobert commented on remix/app/routes/auth.google.callback.tsx
> +    failureRedirect: '/',
This can wait then the next PR then :-)

2023-05-30 03:12 UTC, olivierobert approved these changes

2023-05-30 03:13 UTC, merged